enhancement:
  - changed-files:
      - any-glob-to-any-file: 
          - 'src/**'

test:
  - changed-files:
      - any-glob-to-any-file: 
          - 'tests/**'
          - '**/*.test.ts'
          - 'jest.config.js'

documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - '**/*.md'
          - 'docs/**'

ci:
  - changed-files:
      - any-glob-to-any-file: 
          - '.github/**'

build:
  - changed-files:
      - any-glob-to-any-file: 
          - 'package.json'
          - 'package-lock.json'
          - 'tsconfig.json'
