# ============================================
# Complete Kubernetes Example for Migration Testing
# ============================================

# 1. Namespace - Source
---
apiVersion: v1
kind: Namespace
metadata:
  name: source
  labels:
    environment: development
    team: platform

# 1b. Namespace - Destination (empty, ready for migration)
---
apiVersion: v1
kind: Namespace
metadata:
  name: dest
  labels:
    environment: development
    team: platform

# 2. ConfigMap - Application Configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: source
  labels:
    app: webapp
data:
  database.host: "postgres.source.svc.cluster.local"
  database.port: "5432"
  app.environment: "development"
  app.log.level: "info"
  nginx.conf: |
    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

# 3. Secret - Database Credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: source
  labels:
    app: webapp
type: Opaque
data:
  # username: admin (base64)
  username: YWRtaW4=
  # password: SuperSecret123! (base64)
  password: U3VwZXJTZWNyZXQxMjMh
  # connection-string: postgresql://admin:SuperSecret123!@postgres:5432/mydb (base64)
  connection-string: cG9zdGdyZXNxbDovL2FkbWluOlN1cGVyU2VjcmV0MTIzIUBwb3N0Z3Jlczo1NDMyL215ZGI=

# 4. Secret - TLS Certificate
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-cert
  namespace: source
  labels:
    app: webapp
type: kubernetes.io/tls
data:
  # Fake TLS cert and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lVRmFrZVRMU0NlcnRpZmljYXRlRm9yVGVzdGluZzAeFw0yNDAxMDEwMDAwMDBaFw0yNTAxMDEwMDAwMDBaMBQxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKfakecertdata==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQWtmYWtla2V5ZGF0YQ==

# 5. PersistentVolume (using hostPath for local testing)
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/source-storage"
    type: DirectoryOrCreate

# 6. PersistentVolumeClaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-data-pvc
  namespace: source
  labels:
    app: webapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

# 7. Deployment - Backend Application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: source
  labels:
    app: webapp
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
      tier: backend
  template:
    metadata:
      labels:
        app: webapp
        tier: backend
    spec:
      containers:
      - name: backend
        image: node:18-alpine
        command: ["sh", "-c", "echo 'Starting backend...' && sleep infinity"]
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        - name: config-volume
          mountPath: /app/config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - echo
            - "alive"
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - echo
            - "ready"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: source-data-pvc
      - name: config-volume
        configMap:
          name: app-config

# 8. Deployment - Frontend (Nginx)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: source
  labels:
    app: webapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: app-config
          items:
          - key: nginx.conf
            path: nginx.conf

# 9. Service - Backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: source
  labels:
    app: webapp
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: webapp
    tier: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http

# 10. Service - Frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: source
  labels:
    app: webapp
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: webapp
    tier: frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

# 11. Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: source
  labels:
    app: webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - webapp.local
    secretName: tls-cert
  rules:
  - host: webapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000

# 12. Job to populate PVC with data
---
apiVersion: batch/v1
kind: Job
metadata:
  name: data-initializer
  namespace: source
  labels:
    app: webapp
spec:
  template:
    spec:
      containers:
      - name: initializer
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Initializing data volume..."
          echo "Sample data file 1" > /data/file1.txt
          echo "Sample data file 2" > /data/file2.txt
          echo '{"users": ["alice", "bob", "charlie"]}' > /data/users.json
          mkdir -p /data/logs
          echo "Application started at $(date)" > /data/logs/app.log
          echo "Data initialization complete!"
          ls -la /data
        volumeMounts:
        - name: app-data
          mountPath: /data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: source-data-pvc
      restartPolicy: Never
  backoffLimit: 3
